# Generated by Django 5.0.3 on 2024-05-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_choice', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price_range', models.PositiveIntegerField()),
                ('km_range', models.PositiveIntegerField()),
                ('yearmodel_range', models.PositiveIntegerField()),
            ],
        ),
    ]
