# Generated by Django 5.0.3 on 2024-05-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carselection',
            name='car_choice',
            field=models.CharField(choices=[('Mazda', 'Mazda'), ('Toyota', 'Toyota'), ('Susuki', 'Susuki'), ('Renault', 'Renault'), ('Chevrolet', 'Chevrolet')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carselection',
            name='location',
            field=models.CharField(choices=[('Antioquia', 'Antioquia'), ('Nariño', 'Nariño'), ('Valle Del Cauca', 'Valle Del Cauca'), ('Risaralda', 'Risaralda'), ('Boyaca', 'Boyaca'), ('Bogotá D.C.', 'Bogotá D.C.'), ('Cundinamarca', 'Cundinamarca'), ('Atlántico', 'Atlántico'), ('Caldas', 'Caldas'), ('Norte De Santander', 'Norte De Santander'), ('Santander', 'Santander'), ('Meta', 'Meta'), ('Cesar', 'Cesar'), ('Huila', 'Huila'), ('Tolima', 'Tolima'), ('Córdoba', 'Córdoba'), ('Bolívar', 'Bolívar'), ('Casanare', 'Casanare'), ('Quindio', 'Quindio')], max_length=50),
        ),
    ]
